[versions]
kotest = "6.1.2"
kotlin = "2.2.21"

[libraries]
# Spring
spring-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-webtestclient = { module = "org.springframework.boot:spring-boot-webtestclient" }

kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

# Kotest
kotest-spring = { module = "io.kotest:kotest-extensions-spring", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version = "4.0.2" }
dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }

[bundles]
kotest = [
    "kotest-assertions",
    "kotest-runner-junit5",
    "kotest-spring"
]

spring = [
    "spring-webflux",
    "spring-actuator",
    "kotlin-reflect"
]

spring-test = [
    "spring-test",
    "spring-webtestclient",
]
